### ISSUE TITLE
Instructions for building from source?

### ISSUE THREAD

**Issue by HWaymentSteele** [keio-bioinformatics/mxfold2#7]
Hi, can you provide instructions for building from source the latest in this repo? Thank you!

**Comment by amberT15** [comment]
Yes following up on this, when trying to compile from the current github code i get this error:
`Building wheel for mxfold2 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      A setup.py file already exists. Using it.
      Traceback (most recent call last):
        File "/home/amber/tf_2/lib/python3.8/site-packages/mxfold2/setup.py", line 37, in <module>
          from build import *
        File "/home/amber/tf_2/lib/python3.8/site-packages/mxfold2/build.py", line 3, in <module>
          import pybind11
      ModuleNotFoundError: No module named 'pybind11'`

Manually install pybind11 or pybind11[global] doesnt fix the issue. Would really like to use the newest function of outputting  basepair probabilities. Thanks in advance.

**Comment by jxmelody** [comment]
Hi @amberT15 @yiyingHu @HWaymentSteele,
 As far as I know, this project was built and maintained by **poetry**, 
if you haven't installed poetry yet, you can install it by:
```shell
curl -sSL https://install.python-poetry.org | python3 -
```
Then you need to cd into the root directory of this project and run:
```shell
poetry install
```
to install all these dependencies. 
After the successful installation, you are able to run **predict** and **train** by:
```shell
poetry run python -m mxfold2 train <args>
```

I hope that helps!
